import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { Resend } from "npm:resend"

const resend = new Resend(Deno.env.get("RESEND_API_KEY"))

serve(async (req) => {
  // Handle CORS preflight requests
      if (req.method === "OPTIONS") {
              return new Response(null, {
                        status: 204,
                        headers: {
                                    "Access-Control-Allow-Origin": "*",
                                    "Access-Control-Allow-Methods": "POST, OPTIONS",
                                    "Access-Control-Allow-Headers": "Content-Type, Authorization",
                        },
              })
      }

      if (req.method !== "POST") {
              return new Response("Method not allowed", { status: 405 })
      }
        try {
              const { email, confirmationUrl, userName } = await req.json()

      const data = await resend.emails.send({
            from: "noreply@movidologistics.uk",              to: email,
              subject: "Verify your Movido account",
              html: `
                      <!DOCTYPE html>
                              <html>
                                        <head>
                                                    <style>
                                                                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f1419; color: #e0e0e0; }
                                                                                .container { max-width: 600px; margin: 0 auto; padding: 20px; background: #1a1f2e; border: 1px solid #2d3748; border-radius: 8px; }
                                                                                              .header { text-align: center; margin-bottom: 30px; }
                                                                                                            .logo { font-size: 24px; font-weight: bold; color: #00d4ff; }
                                                                                                                          .content { margin: 20px 0; line-height: 1.6; }
                                                                                                                                        .button {
                                                                                                                                                        display: inline-block;
                                                                                                                                                                        padding: 12px 30px;
                                                                                                                                                                                        background: #00d4ff;
                                                                                                                                                                                                        color: #000;
                                                                                                                                                                                                                        text-decoration: none;
                                                                                                                                                                                                                                        border-radius: 6px;
                                                                                                                                                                                                                                                        font-weight: bold;
                                                                                                                                                                                                                                                                        margin: 20px 0;
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                    .footer { text-align: center; font-size: 12px; color: #888; margin-top: 30px; padding-top: 20px; border-top: 1px solid #2d3748; }
                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                          </head>
                                                                                                                                                                                                                                                                                                                                    <body>
                                                                                                                                                                                                                                                                                                                                                <div class="container">
                                                                                                                                                                                                                                                                                                                                                              <div class="header">
                                                                                                                                                                                                                                                                                                                                                                              <div class="logo">🚚 MOVIDO</div>
                                                                                                                                                                                                                                                                                                                                                                                              <p style="margin: 10px 0 0 0; color: #888;">HGV Fleet Management</p>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="content">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Hello ${userName || email},</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Welcome to Movido! Please verify your email address to complete your registration.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="${confirmationUrl}" class="button">Verify Email</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Or copy and paste this link:</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style="word-break: break-all; color: #00d4ff; font-size: 12px;">${confirmationUrl}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style="margin-top: 30px; color: #888; font-size: 14px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            This link expires in 24 hours.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>© 2026 Movido. All rights reserved.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>HGV Fleet Management & Dispatch Software</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `,
      })

      return new Response(JSON.stringify(data), {
              headers: { "Content-Type": "application/json" },
              status: 200,
      })
        } catch (error) {
              console.error("Email send error:", error)
              return new Response(JSON.stringify({ error: error.message }), {
                      headers: { "Content-Type":i m"paoprptl i{c asteirovne/ j}s ofnr"o m} ,"
                        h t t p s : /s/tdaetnuos.:l a5n0d0/,s
          t d @ 0 .}1)6
  8 . 0}/
      h}t)tp/server.ts"
import { Resend } from "npm:resend"

const resend = new Resend(Deno.env.get("RESEND_API_KEY"))

serve(async (req) => {
    if (req.method !== "POST") {
          return new Response("Method not allowed", { status: 405 })
    }

        try {
              const { email, confirmationUrl, userName } = await req.json()

      const data = await resend.emails.send({
              from: "noreply@movidologistics.uk",
              to: email,
              subject: "Verify your Movido account",
              html: `
                      <!DOCTYPE html>
                              <html>
                                        <head>
                                                    <style>
                                                                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f1419; color: #e0e0e0; }
                                                                                .container { max-width: 600px; margin: 0 auto; padding: 20px; background: #1a1f2e; border: 1px solid #2d3748; border-radius: 8px; }
                                                                                              .header { text-align: center; margin-bottom: 30px; }
                                                                                                            .logo { font-size: 24px; font-weight: bold; color: #00d4ff; }
                                                                                                                          .content { margin: 20px 0; line-height: 1.6; }
                                                                                                                                        .button {
                                                                                                                                                        display: inline-block;
                                                                                                                                                                        padding: 12px 30px;
                                                                                                                                                                                        background: #00d4ff;
                                                                                                                                                                                                        color: #000;
                                                                                                                                                                                                                        text-decoration: none;
                                                                                                                                                                                                                                        border-radius: 6px;
                                                                                                                                                                                                                                                        font-weight: bold;
                                                                                                                                                                                                                                                                        margin: 20px 0;
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                    .footer { text-align: center; font-size: 12px; color: #888; margin-top: 30px; padding-top: 20px; border-top: 1px solid #2d3748; }
                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                          </head>
                                                                                                                                                                                                                                                                                                                                    <body>
                                                                                                                                                                                                                                                                                                                                                <div class="container">
                                                                                                                                                                                                                                                                                                                                                              <div class="header">
                                                                                                                                                                                                                                                                                                                                                                              <div class="logo">🚚 MOVIDO</div>
                                                                                                                                                                                                                                                                                                                                                                                              <p style="margin: 10px 0 0 0; color: #888;">HGV Fleet Management</p>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="content">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Hello ${userName || email},</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Welcome to Movido! Please verify your email address to complete your registration.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="${confirmationUrl}" class="button">Verify Email</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Or copy a
